SPECIALTIES = [
    "General Physician",
    "Cardiologist",
    "Dermatologist",
    "Neurologist",
    "Orthopedic",
    "Pediatrician",
    "ENT",
    "Gynecologist",
    "Psychiatrist",
    "Dentist",
    "Pulmonologist",
    "Gastroenterologist",
    "Urologist",
    "Ophthalmologist",
    "Endocrinologist",
]

SCHEDULE_DAYS = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}

EMERGENCY_SYMPTOMS = [
    "chest pain",
    "difficulty breathing",
    "shortness of breath",
    "trouble breathing",
    "can't breathe",
    "cant breathe",
    "hard time breathing",
    "loss of consciousness",
    "passed out",
    "unconscious",
    "stroke",
    "face drooping",
    "one side is weak",
    "severe bleeding",
    "severe allergic reaction",
    "anaphylaxis",
    "suicidal",
    "self-harm",
    "heart attack",
    "seizure",
    "uncontrolled bleeding",
    "severe trauma",
    "paralysis",
    "sudden severe headache",
    "poisoning",
    "overdose",
]

SPECIALTY_SYMPTOM_MAP = {
    "headache": ["Neurologist", "General Physician"],
    "migraine": ["Neurologist"],
    "fever": ["General Physician"],
    "cough": ["General Physician", "Pulmonologist"],
    "cold": ["General Physician", "ENT"],
    "stomach": ["Gastroenterologist", "General Physician"],
    "abdominal": ["Gastroenterologist", "General Physician"],
    "nausea": ["Gastroenterologist", "General Physician"],
    "vomiting": ["Gastroenterologist", "General Physician"],
    "diarrhea": ["Gastroenterologist", "General Physician"],
    "back pain": ["Orthopedic", "General Physician"],
    "joint": ["Orthopedic"],
    "bone": ["Orthopedic"],
    "fracture": ["Orthopedic"],
    "skin": ["Dermatologist"],
    "rash": ["Dermatologist"],
    "acne": ["Dermatologist"],
    "heart": ["Cardiologist", "General Physician"],
    "chest": ["Cardiologist", "Pulmonologist", "General Physician"],
    "blood pressure": ["Cardiologist", "General Physician"],
    "dental": ["Dentist"],
    "tooth": ["Dentist"],
    "gum": ["Dentist"],
    "eye": ["Ophthalmologist"],
    "vision": ["Ophthalmologist"],
    "ear": ["ENT"],
    "throat": ["ENT"],
    "sinus": ["ENT"],
    "mental health": ["Psychiatrist", "General Physician"],
    "anxiety": ["Psychiatrist", "General Physician"],
    "depression": ["Psychiatrist", "General Physician"],
    "sleep": ["Psychiatrist", "General Physician"],
    "child": ["Pediatrician"],
    "baby": ["Pediatrician"],
    "infant": ["Pediatrician"],
    "urinary": ["Urologist", "General Physician"],
    "kidney": ["Urologist"],
    "thyroid": ["Endocrinologist", "General Physician"],
    "diabetes": ["Endocrinologist", "General Physician"],
    "weight": ["Endocrinologist", "General Physician"],
    "allergy": ["General Physician", "Dermatologist"],
    "fatigue": ["General Physician"],
    "tired": ["General Physician"],
    "dizziness": ["Neurologist", "General Physician"],
    "anemia": ["General Physician"],
}

DOCTOR_AVATARS = [
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr1&backgroundColor=b6e3f4",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr2&backgroundColor=c0aede",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr3&backgroundColor=d1d4f9",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr4&backgroundColor=ffd5dc",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr5&backgroundColor=b6e3f4",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr6&backgroundColor=c0aede",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr7&backgroundColor=d1d4f9",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Dr8&backgroundColor=ffd5dc",
]

PATIENT_AVATARS = [
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pt1&backgroundColor=b6e3f4",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pt2&backgroundColor=c0aede",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pt3&backgroundColor=d1d4f9",
    "https://api.dicebear.com/7.x/avataaars/svg?seed=Pt4&backgroundColor=ffd5dc",
]

URGENCY_LEVELS = {
    "low": {"color": "green", "label": "Low Urgency", "icon": ":material/check_circle:"},
    "moderate": {"color": "orange", "label": "Moderate", "icon": ":material/warning:"},
    "high": {"color": "red", "label": "High Urgency", "icon": ":material/error:"},
    "emergency": {"color": "red", "label": "Emergency", "icon": ":material/emergency:"},
}

APPOINTMENT_STATUSES = {
    "booked": {"color": "blue", "icon": ":material/event:"},
    "confirmed": {"color": "green", "icon": ":material/check_circle:"},
    "completed": {"color": "gray", "icon": ":material/task_alt:"},
    "cancelled": {"color": "red", "icon": ":material/cancel:"},
    "no_show": {"color": "orange", "icon": ":material/person_off:"},
}
